REVOKE ALL ON FUNCTION public.cap_self_reported_xp() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.evaluate_adaptive_coach_game_outcome() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.evaluate_adaptive_focus_forecast() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.evaluate_daily_outlook_from_passive_focus() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.guard_profile_sensitive_fields() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.prevent_self_role_assignment() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.touch_content_activity() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.touch_reason_session_activity() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.touch_s2_game_activity() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_updated_at_column() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_active_subscription(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_active_subscription(uuid, text) TO authenticated;